-- Player Table
CREATE TABLE IF NOT EXISTS Players (
    `PlayerID` INT AUTO_INCREMENT PRIMARY KEY,
    `UserID` INT,
    `SummonerName` VARCHAR(255) NOT NULL UNIQUE,
    `PUUID` VARCHAR(255) NOT NULL UNIQUE,
    `AccountID` VARCHAR(255) NOT NULL UNIQUE,
    `SummonerID` VARCHAR(255) NOT NULL UNIQUE,
    `Level` INT NOT NULL,
    `SummonerIcon` VARCHAR(255) NOT NULL,
    `Updated` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`UserID`) REFERENCES Users(`UserID`)
);